name: espejo-build-push-ghcr

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push apt-mirror
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/apt-mirror.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/espejo_apt-mirror:latest
      -
        name: Build and push bandersnatch
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/bandersnatch.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/espejo_bandersnatch:latest
      -
        name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/nginx.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/espejo_nginx:latest
