name: espejo-build-push-ghcr

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  repository_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest
  IMAGE_PLATFORM: linux/amd64
  REPO_CONTEXT: .
  APT_MIRROR_CONTAINERFILE: ./Dockerfiles/apt-mirror.Dockerfile
  APT_MIRROR_NAME: espejo_apt-mirror
  BANDERSNATCH_CONTAINERFILE: ./Dockerfiles/bandersnatch.Dockerfile
  BANDERSNATCH_NAME: espejo_bandersnatch
  NGINX_CONTAINERFILE: ./Dockerfiles/nginx.Dockerfile
  NGINX_NAME: espejo_nginx

jobs:
  buildah:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      -
        name: Cancel previous run in progress
        id: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        id: repo-checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2
      -
        name: Log in to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build apt-mirror
        id: build-apt-mirror-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APT_MIRROR_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: |
            ${{ env.APT_MIRROR_CONTAINERFILE }}
          platforms: |
            ${{ env.IMAGE_PLATFORM }}
      -
        name: Build bandersnatch
        id: build-bandersnatch-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.BANDERSNATCH_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: |
            ${{ env.BANDERSNATCH_CONTAINERFILE }}
          platforms: |
            ${{ env.IMAGE_PLATFORM }}
      -
        name: Build nginx
        id: build-nginx-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NGINX_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          context: ${{ env.REPO_CONTEXT }}
          containerfiles: |
            ${{ env.NGINX_CONTAINERFILE }}
          platforms: |
            ${{ env.IMAGE_PLATFORM }}
      -
        name: Push apt-mirror
        id: push-apt-mirror-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-apt-mirror-image.outputs.image }}
          tags: ${{ steps.build-apt-mirror-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
      -
        name: Push bandersnatch
        id: push-bandersnatch-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-bandersnatch-image.outputs.image }}
          tags: ${{ steps.build-bandersnatch-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
      -
        name: Push nginx
        id: push-nginx-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-nginx-image.outputs.image }}
          tags: ${{ steps.build-nginx-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}