---
name: espejo-build-push-ghcr

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:
  build-apt-mirror-image:
    name: Call Docker Build for apt mirror
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./Dockerfiles/apt-mirror.Dockerfile
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/espejo_apt-mirror
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64
  build-bandersnatch-image:
    name: Call Docker Build for bandersnatch
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./Dockerfiles/bandersnatch.Dockerfile
      cancel-previous-runs: false
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/espejo_bandersnatch
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64
  build-nginx-image:
    name: Call Docker Build for apt nginx
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./Dockerfiles/nginx.Dockerfile
      cancel-previous-runs: false
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/espejo_nginx
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64
